version: '3.9'
services:
  backend:
    build: .
    ports: 
      - '8081:8080'
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'  
    volumes: 
      - .dbdata:/var/lib/postgresql/data  
volumes:
  db:
    driver: local      